# -- Google Client Id. You **must** provide this value to make this plugin work
# Besides, this id. You also need to provide `googleClientSecret` via secret `oauth-secrets` (key: google-client-secret).
# You can use [Magda Create Secret Tool](https://www.npmjs.com/package/@magda/create-secrets) to create this secret.
googleClientId:

# -- only for providing appropriate default value for helm lint
global:
  image: {}
  rollingUpdate: {}
  externalUrl: ""
  authPluginRedirectUrl: "/sign-in-redirect"

# -- the redirection url after the whole authentication process is completed.
# Authentication Plugins will use this value as default.
# The following query paramaters can be used to supply the authentication result:
# <ul>
# <li>result: (string) Compulsory. Possible value: "success" or "failure". </li>
# <li>errorMessage: (string) Optional. Text message to provide more information on the error to the user. </li>
# </ul>
# This field is for overriding the value set by `global.authPluginRedirectUrl`.
# Unless you want to have a different value only for this auth plugin, you shouldn't set this value.
authPluginRedirectUrl:

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.minions.image.x
# - Values.global.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

autoscaler:
  # -- turn on the autoscaler or not
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

image: 
  # -- default docker image name
  name: "magda-auth-google"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  imagePullSecret: false

# -- no. of initial replicas
replicas: 1

# -- which system account we used to talk to auth api
# The value of this field will only be used when `global.defaultAdminUserId` has no value
defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 50m